version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        uid: 1000
        user: sail
    image: kupon-app
    container_name: kupon-app
    restart: unless-stopped
    working_dir: /var/www/laravel
    volumes:
      - ./:/var/www
    networks:
      - kupon_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: kupon-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - kupon_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: kupon-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-kupon}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-user}
    volumes:
      - kupon_db_data:/var/lib/mysql
    ports:
      - "33061:3306" # Expose on a different host port if 3306 is in use
    networks:
      - kupon_network

  adminer:
    image: phpmyadmin
    container_name: kupon-adminer
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME:-user}
      PMA_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "8080:80"
    networks:
      - kupon_network

networks:
  kupon_network:
    driver: bridge

volumes:
  kupon_db_data:
    driver: local
